DROP DATABASE IF EXISTS LIBRARY_SYSTEM;
CREATE DATABASE IF NOT EXISTS LIBRARY_SYSTEM;

USE LIBRARY_SYSTEM;

DROP TABLE IF EXISTS RAW_DATA;
CREATE TABLE RAW_DATA (
    ISBN VARCHAR(10),
    ISBN13 VARCHAR(13),
    Title VARCHAR(255),
    Author VARCHAR(255),
    COVER VARCHAR(255),
    PUBLISHER VARCHAR(255),
    PAGES INT
);

--  ID0000id,ssn,first_name,last_name,email,address,city,state,phone
DROP TABLE IF EXISTS RAW_BORROWER_DATA;
CREATE TABLE RAW_BORROWER_DATA (
    Card_ID VARCHAR(20),
    Ssn VARCHAR(11),
    Fname VARCHAR(255),
    Lname VARCHAR(255),
    Email VARCHAR(255),
    Address VARCHAR(255),
    City VARCHAR(255),
    State VARCHAR(255),
    Phone VARCHAR(14)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (
    ISBN VARCHAR(10),
    Title VARCHAR(255),
    CONSTRAINT PK_BOOKS PRIMARY KEY (ISBN)
);

DROP TABLE IF EXISTS BOOK_AUTHORS;
CREATE TABLE BOOK_AUTHORS (
    Author_ID INT AUTO_INCREMENT,
    ISBN VARCHAR(10),
    CONSTRAINT PK_BOOK_AUTHORS PRIMARY KEY (Author_ID),
    CONSTRAINT FK_BOOK FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS (
    Author_ID INT,
    FName VARCHAR(255),
    Minit VARCHAR(1),
    LName VARCHAR(255),
    CONSTRAINT PK_AUTHORS PRIMARY KEY (Author_ID),
    FOREIGN KEY (Author_ID) REFERENCES BOOK_AUTHORS(Author_ID)
);

-- Please change the following directory to be where your books.csv file is located 
DROP TABLE IF EXISTS BOOK_LOANS;
CREATE TABLE BOOK_LOANS (
    Loan_ID INT,
    ISBN VARCHAR(10),
    Card_ID VARCHAR(6),
    Date_out DATE,
    Due_date DATE,
    Date_in DATE,
    CONSTRAINT PK_BOOKLOANS PRIMARY KEY (Loan_ID),
    CONSTRAINT FK_BORROWER FOREIGN KEY (Card_ID) REFERENCES BORROWER(Card_ID)
);

DROP TABLE IF EXISTS FINES;
CREATE TABLE FINES (
    Loan_ID INT,
    Fine_amt DOUBLE,
    Paid DOUBLE,
    CONSTRAINT FK_BOOK_LOANS FOREIGN KEY (Loan_ID) REFERENCES BOOK_LOANS(Loan_ID)
);

DROP TABLE IF EXISTS BORROWER;
CREATE TABLE BORROWER (
    Card_ID VARCHAR(6),
    Ssn VARCHAR(11),
    Bname VARCHAR(255),
    Address VARCHAR(255),
    Phone VARCHAR(14),
    CONSTRAINT PK_BORROWER PRIMARY KEY (Card_ID)
);

LOAD DATA LOCAL INFILE '/Users/thebenzsecrets/CS4347_Team_Project/books.csv'
INTO TABLE RAW_DATA
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/Users/thebenzsecrets/CS4347_Team_Project/borrowers.csv'
INTO TABLE RAW_BORROWER_DATA
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
ESCAPED BY '\\'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

INSERT INTO BOOKS (ISBN, Title)
SELECT DISTINCT ISBN, Title
FROM RAW_DATA;

INSERT INTO BOOK_AUTHORS (ISBN)
SELECT DISTINCT ISBN
FROM RAW_DATA;

INSERT INTO BORROWER (Card_ID, Ssn, Bname, Address, Phone)
SELECT
    RIGHT(REGEXP_REPLACE(TRIM(Card_ID), '[^0-9]', ''), 6) AS Card_ID,
    TRIM(Ssn) AS Ssn,
    CONCAT_WS(' ', TRIM(Fname), TRIM(Lname)) AS Bname,
    TRIM(Address) AS Address,
    REGEXP_REPLACE(COALESCE(Phone,''), '[^0-9]', '') AS Phone
FROM RAW_BORROWER_DATA;

INSERT INTO AUTHORS (Author_ID, FName, Minit, LName)
SELECT BA.Author_ID,
       TRIM(SUBSTRING_INDEX(RD.Author, ' ', 1)) AS FName,
       CASE
           WHEN (LENGTH(RD.Author) - LENGTH(REPLACE(RD.Author, ' ', ''))) > 1
           THEN LEFT(SUBSTRING_INDEX(SUBSTRING_INDEX(RD.Author, ' ', 2), ' ', -1), 1)
           ELSE NULL
       END AS Minit,
       TRIM(SUBSTRING_INDEX(RD.Author, ' ', -1)) AS LName
FROM RAW_DATA RD
JOIN BOOK_AUTHORS BA ON RD.ISBN = BA.ISBN;

DROP TABLE IF EXISTS RAW_DATA;
