DROP DATABASE IF EXISTS LIBRARY_SYSTEM;
CREATE DATABASE IF NOT EXISTS LIBRARY_SYSTEM;

USE LIBRARY_SYSTEM;

DROP TABLE IF EXISTS RAW_DATA;
CREATE TABLE RAW_DATA (
    ISBN VARCHAR(10),
    ISBN13 VARCHAR(13),
    Title VARCHAR(255),
    Author VARCHAR(255),
    COVER VARCHAR(255),
    PUBLISHER VARCHAR(255),
    PAGES INT
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (
    ISBN VARCHAR(10),
    Title VARCHAR(255),
    CONSTRAINT PK_BOOKS PRIMARY KEY (ISBN)
);

DROP TABLE IF EXISTS BOOK_AUTHORS;
CREATE TABLE BOOK_AUTHORS (
    Author_ID INT AUTO_INCREMENT,
    ISBN VARCHAR(10),
    CONSTRAINT PK_BOOK_AUTHORS PRIMARY KEY (Author_ID),
    CONSTRAINT FK_BOOK FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS (
    Author_ID INT,
    FName VARCHAR(255),
    Minit VARCHAR(1),
    LName VARCHAR(255),
    CONSTRAINT PK_AUTHORS PRIMARY KEY (Author_ID),
    FOREIGN KEY (Author_ID) REFERENCES BOOK_AUTHORS(Author_ID)
);

LOAD DATA LOCAL INFILE '/Users/lynn/Documents/School/2025 Fall/Database Systems/Library System/books.csv'
INTO TABLE RAW_DATA
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

INSERT INTO BOOKS (ISBN, Title)
SELECT DISTINCT ISBN, Title
FROM RAW_DATA;

INSERT INTO BOOK_AUTHORS (ISBN)